import type { Hotel } from "#phaser/domain/Hotel";

export default async function getHotel(_userId: string): Promise<Hotel> {
	return {
		gold: 1_000,
		rooms: {
			lobby: {
				id: "lobby",
				type: "lobby",
				position: { x: 0, y: -1 },
				client: null,
			},
			room_0_0: {
				id: "room_0_0",
				type: "bedroom",
				position: { x: 0, y: 0 },
				client: {
					id: "client1",
					name: "client1",
					type: "poring",
					satisfaction: 15,
					likes: ["heat"],
					produces: ["cold"],
				},
			},
			room_0_1: {
				id: "room_0_1",
				type: "bedroom",
				position: { x: 0, y: 1 },
				client: {
					id: "client2",
					name: "client2",
					type: "nice neighbour",
					satisfaction: 15,
					likes: ["noise"],
					produces: ["cold"],
				},
			},
			room_0_2: {
				id: "room_0_2",
				type: "bedroom",
				position: { x: 0, y: 2 },
				client: {
					id: "client3",
					name: "client3",
					type: "angry pear",
					satisfaction: 15,
					likes: ["odor"],
					produces: ["noise"],
				},
			},
			room_0_3: {
				id: "room_0_3",
				type: "bedroom",
				position: { x: 0, y: 3 },
				client: {
					id: "client4",
					name: "client4",
					type: "bomber",
					satisfaction: 15,
					likes: ["cold"],
					produces: ["heat"],
				},
			},
			room_1_0: {
				id: "room_1_0",
				type: "bedroom",
				position: { x: 1, y: 0 },
				client: {
					id: "client5",
					name: "client5",
					type: "mama blob",
					satisfaction: 15,
					likes: ["sunlight"],
					produces: ["odor"],
				},
			},
			room_1_1: {
				id: "room_1_1",
				type: "bedroom",
				position: { x: 1, y: 1 },
				client: {
					id: "client6",
					name: "client6",
					type: "blobling",
					satisfaction: 15,
					likes: ["heat"],
					produces: ["cold"],
				},
			},
			room_1_2: {
				id: "room_1_2",
				type: "bedroom",
				position: { x: 1, y: 2 },
				client: {
					id: "client7",
					name: "client7",
					type: "floor ghost",
					satisfaction: 15,
					likes: ["cold"],
					produces: ["sunlight"],
				},
			},
			room_1_3: {
				id: "room_1_3",
				type: "bedroom",
				position: { x: 1, y: 3 },
				client: {
					id: "client8",
					name: "client8",
					type: "column ghost",
					satisfaction: 15,
					likes: ["noise"],
					produces: ["odor"],
				},
			},
			room_2_0: {
				id: "room_2_0",
				type: "bedroom",
				position: { x: 2, y: 0 },
				client: {
					id: "client9",
					name: "client9",
					type: "schrodingcat",
					satisfaction: 15,
					likes: ["odor"],
					produces: ["noise"],
				},
			},
			room_2_1: {
				id: "room_2_1",
				type: "bedroom",
				position: { x: 2, y: 1 },
				client: {
					id: "client10",
					name: "client10",
					type: "leek",
					satisfaction: 15,
					likes: ["sunlight"],
					produces: ["heat"],
				},
			},
			room_2_2: {
				id: "room_2_2",
				type: "bedroom",
				position: { x: 2, y: 2 },
				client: {
					id: "client11",
					name: "client11",
					type: "repair",
					satisfaction: 15,
					likes: ["heat"],
					produces: ["cold"],
				},
			},
			room_2_3: {
				id: "room_2_3",
				type: "bedroom",
				position: { x: 2, y: 3 },
				client: {
					id: "client12",
					name: "client12",
					type: "vampire",
					satisfaction: 15,
					likes: ["cold"],
					produces: ["sunlight"],
				},
			},
		},
		clientQueue: [
			{
				id: "queue1",
				name: "queue1",
				type: "gem chicken",
				likes: ["heat"],
				produces: ["noise"],
			},
			{
				id: "queue2",
				name: "queue2",
				type: "monop'guy",
				likes: ["cold"],
				produces: ["odor"],
			},
			{
				id: "queue3",
				name: "queue3",
				type: "inspector",
				likes: ["sunlight"],
				produces: ["heat"],
			},
			{
				id: "queue4",
				name: "queue4",
				type: "cuddle bomb",
				likes: ["noise"],
				produces: ["cold"],
			},
			{
				id: "queue5",
				name: "queue5",
				type: "dragon",
				likes: ["odor"],
				produces: ["sunlight"],
			},
			{
				id: "queue6",
				name: "queue6",
				type: "diffuser",
				likes: ["heat"],
				produces: ["noise"],
			},
			{
				id: "queue7",
				name: "queue7",
				type: "magic patron",
				likes: ["cold"],
				produces: ["odor"],
			},
			{
				id: "queue8",
				name: "queue8",
				type: "evil santa",
				likes: ["sunlight"],
				produces: ["heat"],
			},
		],
	};
}
